### ISSUE TITLE
auth err

### ISSUE THREAD

**Issue by timh5** [dpjanes/iotdb-smartthings#15]
hi thanks for the awesome tutorial... have a small issue though.

i followed everything:
 - pasted the groovy app
 - enabled oauth
 - did the Oauthorization via your handy online tool
 - ran the python script and get this:

```
python smartthings.py --type motion
{u'message': u'This request is not authorized by the specified access token', u'type': u'AccessDenied', u'error': True}
null
```

i then re-copy and pasted the client id/secret just to check, but same thing...
any ideas of how I could troubleshoot this?

**Comment by timh5** [comment]
nevermind, fixed it... the device url was hardcoded not account accounting for the new way of using different subdomains "https://graph-na02-useast1.api.smar...."  ... which is returned in the endpoint request.

**Comment by dpjanes** [comment]
Is there some code fix I should be implementing?

**Comment by timh5** [comment]
i'll look into it and submit a patch.
