### ISSUE TITLE
Failed reading config file: SyntaxError: Unexpected token   in JSON at position 26

### ISSUE THREAD

**Issue by reh8388** [dpjanes/iotdb-smartthings#17]
Having issues with the config file. I have cleared all files and started with a fresh install. I am still unable to get beyond this error. Any help would be appreciated. Exact copy of the config file:

{
    "ip": "192.168.0.3”,
    "port": "39500"
}

**Comment by dpjanes** [comment]
Perhaps you can post the error

**Comment by reh8388** [comment]
Sorry it wasn't clear. The title was the error. I am assuming at this point my text editor was doing some sort of EOL conversion as I changed my IP on the hub to match the one in the example file so I didn't have to modify the file and that has gotten me past the error.

"Failed reading config file: SyntaxError: Unexpected token in JSON at position 26"

**Comment by dpjanes** [comment]
No stack trace? What command are you running? 

Also just for fun - assuming you're using Python- try this, replacing sample.json with whatever JSON files you've created.

python -c "import json; json.load(open('sample.json'))"
