### ISSUE TITLE
Error while looking for presence 

### ISSUE THREAD

**Issue by elN1n0** [dpjanes/iotdb-smartthings#21]
Traceback (most recent call last):
  File "smartthings.py", line 209, in <module>
    ds = st.request_devices(options.device_type)
  File "smartthings.py", line 119, in request_devices
    SmartThings.raise_api_errors(self.deviceds)
  File "smartthings.py", line 55, in raise_api_errors
    raise Exception(error_type + ": " + error_message)
Exception: java.lang.NullPointerException: An unexpected error occurred.

**Comment by TomerFi** [comment]
I have the exact same issue when looking for presence.
When running `python smartthings.py --type presence` with Python 2.7.14, I get the following error:
```
Traceback (most recent call last):
  File "smartthings.py", line 209, in <module>
    ds = st.request_devices(options.device_type)
  File "smartthings.py", line 119, in request_devices
    SmartThings.raise_api_errors(self.deviceds)
  File "smartthings.py", line 55, in raise_api_errors
    raise Exception(error_type + ": " + error_message)
Exception: java.lang.NullPointerException: An unexpected error occurred.
```

I have only one device attached to my smartthings account, my iphone as presence sensor.

**Comment by TomerFi** [comment]
I've deleted everything and rebuilt it following the guide and now the error is gone, so I guess it was my bad.

Nevertheless now I always get an empty list each time I'm trying to list my `presence` devices.

**Comment by TomerFi** [comment]
Figured it out (sorry, I'm new to smarthings).
In `smartthings.groovy` line 359:
```groovy
def jd = [id: device.id, label: device.label, type: type, value: vd, hub: device.hub.name];
```

I only have one device connected to my smartthings hub, my phone which is of type `Mobile Presence` and is not set to any hub, therefore the above code failed.
I've change it to:
```groovy
def hub_name = "None"
if (device.hub) {
	hub_name = device.hub.name
}
def jd = [id: device.id, label: device.label, type: type, value: vd, hub: hub_name];
```

**Comment by dpjanes** [comment]
Great. It's been a long time since I looked at this code, can't you just do something like this in Groovy

```groovy
def jd = [id: device.id, label: device.label, type: type, value: vd, hub: device.hub?.name];
```

**Comment by dpjanes** [comment]
This is actually my first and only Groovy code. If you've tested that little code snippet with the `?` I'll update the code base.

**Comment by TomerFi** [comment]
Yes. I've just tested it.
Works like a charm!
:-)

**Comment by dpjanes** [comment]
Cheers!
