### ISSUE TITLE
Trouble with Initial Setup

### ISSUE THREAD

**Issue by smerdonw** [dpjanes/iotdb-smartthings#23]
I need some help. I suspect that homebridge is not loading. I'm trying to install on my MacBook Pro first to get my feet wet before final setup on a Raspberry Pi 3. I wanted to first separate the base homebridge functionality from smartthings, but not sure if there is a simple config to use to ensure it is loading.

I've installed homebridge and the smartthings npm per instructions. When I start homebridge it says:

Loaded plugin: homebridge-smartthings
Registering platform 'homebridge-smartthings.SmartThings'
---
Loaded config.json with 0 accessories and 0 platforms.

The config.json looks like this which is validated...

{
	"bridge": {
		"name": "Homebridge MacBook Pro",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "xxx-xx-xxx"
	},

	"description": "Smartthings running on MacBook Pro.",

	"platform": "SmartThings",
	 "name": "SmartThings",
		 "app_url": "https://graph.api.smartthings.com:443/api/smartapps/installations/",
		 "app_id": "**************************************************",
		 "access_token": "******************************************************",
		 "polling_seconds": 3600,
		 "update_method": "direct",
		 "direct_ip": "xxx.xxx.xxx.xxx",
		 "direct_port": 8000,
		 "api_seconds": 30,
		 "excluded_capabilities": {
				 "SMARTTHINGS-DEVICE-ID-1" : [
						 "Switch",
						 "Temperature Measurement"
				 ]}
}

**Comment by dpjanes** [comment]
You should probably open this in Homebridge, I don't know anything about that.
