### ISSUE TITLE
Control a virtual contact 

### ISSUE THREAD

**Issue by BluGeni** [dpjanes/iotdb-smartthings#4]
I am trying to control a contact switch on the hub with this, I have everything working but am unable to change the status of the contact switch:

I am doing this:

 python smartthings.py --type contact --id "myid" --request contact=true

and get this back:

{'device': {u'id': u'myid',
            u'label': u'Garage Door',
            u'mqtt': u'tcp://mqtt.iotdb.org/u//st/contact/mqttID',
            u'type': u'contact',
            'url': u'https://graph.api.smartthings.com/api/smartapps/installations/id',
            u'value': {u'contact': False, u'timestamp': None}},
 'request': {'contact': 'true'}}

Any advice?

**Comment by dpjanes** [comment]
Contact Switches are read-only, are they not? They just report a state, and
hence there's no way to manipulate that (except physically).

D.

**Comment by BluGeni** [comment]
I guess I dont know. Its looking like that may be the case. I new to SmartThings so I am still learning how everything works. Its looking like I may need to make a custom device handler to accomplish what I am trying to do: Send a command from python to ST hub to change the state of a sensor. I want to do this because I have a raspberry pi setup already monitoring my garage with a cheap reed switch and would rather use my existing setup and just incorporate it into ST. Let me know if you have any pointers or place to start. This repo is really nice too btw.

**Comment by dpjanes** [comment]
I don't think you'll be able to change the state of a sensor on
SmartThings, as they're probably inherently read-only.

If you want to try more of my software - and I think this is really worth
your while - install HomeStar on your Pi.
https://homestar.io/about
